### ISSUE TITLE
Should "instance" be necessary for singletons?

### ISSUE THREAD

**Issue by Brinsky** [TeamShadow/shadow#16]
Currently, the `instance` keyword is necessary to access the object of a given singleton, as in
```
Console:instance.printLine("Hello!");
```
While this is very explicit, it might be unnecessarily verbose and frustrating to programmers. The Java-style syntax for accessing static members seems like a potential replacement:
```
Console.printLine("Hello!");
```
It seems feasible for the compiler to detect whether or not a given singleton is used within a given program, and - if necessary - to perform its instantiation at the start of the program.

**Comment by bwittman** [comment]
There are some implementation questions.  My preference would probably be to initialize a singleton in the first method in which it's used.  The check against `null` can be done at the beginning of each method, avoiding the latency of lots of singletons getting initialized at the beginning of the program.  Admittedly, it could probably be done either way.

Another important question is whether or not we can "declare" singletons for convenience:

    Console io;
    io.printLine("Hello!");

Although this syntax is reasonable, are singletons objects that can be stored into regular references, as follows?

    Object o = Console; //yuck
    CanPrintLine interfaceReferenc = Console;

I can't think of a use case, and it begins to cause problems with `freeze()` and future plans for thread communication, since we can't make an immutable singleton and singletons are per-thread only.  I would lean toward the first syntax and away from the second.

**Comment by bwittman** [comment]
The `instance` keyword has been removed.  Now, singletons can be "declared" at local or class scope, although such variables do not correspond to a real object.  Instead, the singleton is loaded as needed.  The current implementation creates singletons (if needed) at the beginning of any method call that contains a singleton usage.
