### ISSUE TITLE
get updated compiler?

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#26]
I was working with Dr. Wittman earlier on updating my compiler. I have some code that keeps seg faulting (that I'm like 85% sure should work) but since I'm not using the latest compiler I can't be sure whatever issue it is hasn't already been fixed.  I cloned the shadow repo and I have maven installed. It might be tough for me to find either of you in person, so I was hoping someone could help me on here?

**Comment by Brinsky** [comment]
Just a quick installation guide here for anyone who views this issue in the future:

In order to build the Shadow compiler into a jar, take the following steps:
- Install Apache Maven (version 3.3.3 has been verified to work, but many prior and later versions should work)
- Clone the main compiler repository with `git clone git://github.com/TeamShadow/shadow.git <output_directory>`, where `<output_directory> is the name of your desired repository folder
- Change directory into the aforementioned `<output_directory>` - this should contain a number of files and folders, including `pom.xml`
- Run the command `mvn package` or, if you'd like to skip the lengthy automated tests, run `mvn package -DskipTests=true`

Following this procedure, a newly created .jar file should exist in `<output_directory>/target`. The compiler can now be used by running this jar with `java -jar <shadowc_jar> <options>`.
