### ISSUE TITLE
Generics casting

### ISSUE THREAD

**Issue by claude-abounegm** [TeamShadow/shadow#45]
Let's assume we have:

```
class Wombat<T> {
   public doSomething(T a) => () {
        Something<T> x = cast<Something<T>>(a);
   }
}
```

I believe the cast should be valid; however, it isn't and the only way to currently do it is: `cast<Something<T>>(cast<Object>(a))`

Thanks!

**Comment by bwittman** [comment]
This behavior is intentional.  It's supposed to be impossible to cast between any two things in Shadow unless there is a subtype relationship between them.  `T` is not a subtype of `Something<T>`, and `Something<T>` is not a subtype of `T`.  I'm open to argument on this topic, but is this a common use case?  I prefer the deliberate steps needed to warn a user that a cast that doesn't make sense is happening.
